name: ESLint Code Quality Check

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint with reviewdog
      uses: reviewdog/action-eslint@v1
      if: github.event_name == 'pull_request'
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        eslint_flags: '*.js'
        fail_on_error: true
        filter_mode: added

    - name: Run ESLint for manual dispatch
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "Running ESLint on all JavaScript files:"
        npx eslint *.js
        
        # Check for errors
        npx eslint *.js --format json > eslint-results.json || true
        
        error_count=$(node -e "
          const results = require('./eslint-results.json');
          const errorCount = results.reduce((sum, result) => 
            sum + result.messages.filter(msg => msg.severity === 2).length, 0);
          console.log(errorCount);
        ")
        
        echo "ESLint error count: $error_count"
        
        if [ "$error_count" -gt 0 ]; then
          echo "❌ ESLint found $error_count error(s)."
          exit 1
        else
          echo "✅ No ESLint errors found."
        fi